version: '3'
services:
  git:
    image: upc_api:1.0
    container_name: upc_api
    build: .
    command: git -C /build app https://github.com/skythecodemaster/upc-api.git
  app:
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1