version: '3'
services:
  app:
    build: 
      context: https://github.com/SkyTheCodeMaster/upc-api.git#main
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1