version: "3.3"
services:
  upc_api:
    container_name: upc_api
    build: 
      context: https://github.com/SkyTheCodeMaster/upc-api.git
      no_cache: true
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /path/to/config/:/app/config/ # Your config file, example @ /src/config.example.toml
    environment:
      - PYTHONUNBUFFERED=1
networks: {}